TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += procServControl.db
#=======================================
include $(TOP)/configure/RULES
