TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += procServControl.db
#DB_INSTALLS += ipl_expanded.db
#=======================================
include $(TOP)/configure/RULES
